# @package _global_
defaults:
  - override /train: cell

data:
  augmentation_dir: /root/workdir/tile_orion_norm_slides

train:
  epochs: 15
  batch_size: 8
  data_sampler:
    use_sampler: False
  gan_train: false
  wandb_note: "foundation_model_hoptimus"

model:
  model_name: "unet_lora"
  encoder:
    encoder_name: hoptimus0
    encoder_weights: null # null means foundation model encoder for unetr
